version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # TODO: Change this
      MYSQL_DATABASE: analitycs_db
      MYSQL_USER: adm
      MYSQL_PASS: 123456
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql