version: '3.1'

services:
  mysql:
    container_name: mysql_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '123456' # TODO: Change this
      MYSQL_USER: 'adm'
      MYSQL_PASS: '123456'
    ports:
      - "3307:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql